# Generated by Django 4.1.4 on 2022-12-21 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('password', models.CharField(max_length=128, null=True)),
                ('username', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('birth_date', models.DateField(default='1999-01-01')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('descr', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'classes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateField(blank=True, null=True)),
                ('date_of_purchase', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('BOOKED', 'booked'), ('PAID', 'paid'), ('PASSED', 'passed')], max_length=10, null=True)),
                ('id_class', models.ForeignKey(db_column='id_class', on_delete=django.db.models.deletion.DO_NOTHING, to='dance.class')),
                ('id_student', models.ForeignKey(db_column='id_student', on_delete=django.db.models.deletion.CASCADE, related_name='purchase', related_query_name='purchase', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchase',
                'managed': True,
            },
        ),
    ]
