# Generated by Django 4.1.2 on 2022-11-04 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('descr', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'classes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('mail', models.CharField(blank=True, max_length=30, null=True)),
                ('passw', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateField(blank=True, null=True)),
                ('date_of_purchase', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('id_class', models.ForeignKey(db_column='id_class', on_delete=django.db.models.deletion.DO_NOTHING, to='dance.class')),
                ('id_student', models.ForeignKey(db_column='id_student', on_delete=django.db.models.deletion.DO_NOTHING, to='dance.students')),
            ],
            options={
                'db_table': 'purchase',
                'managed': True,
            },
        ),
    ]
