# Generated by Django 4.1.2 on 2022-10-13 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('pic', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'groups',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('info', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trainers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('id_group', models.ForeignKey(db_column='id_group', on_delete=django.db.models.deletion.DO_NOTHING, to='dance.groups')),
            ],
            options={
                'db_table': 'timetable',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_classes', models.IntegerField(blank=True, null=True)),
                ('date_of_purchase', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('id_group', models.ForeignKey(db_column='id_group', on_delete=django.db.models.deletion.DO_NOTHING, to='dance.groups')),
                ('id_student', models.ForeignKey(db_column='id_student', on_delete=django.db.models.deletion.DO_NOTHING, to='dance.students')),
            ],
            options={
                'db_table': 'subscriptions',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='groups',
            name='id_trainer',
            field=models.ForeignKey(db_column='id_trainer', on_delete=django.db.models.deletion.DO_NOTHING, to='dance.trainers'),
        ),
    ]
