# Generated by Django 4.1.2 on 2022-11-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
