# Generated by Django 4.1.4 on 2022-12-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0002_alter_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
