# Generated by Django 4.1.2 on 2022-10-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0003_groups_timetable_delete_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='timetable',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
